# Generated by Django 6.1.1 on 2026-09-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(help_text='Nome de dominio do Active Directory', max_length=255, unique=True)),
                ('search_base', models.CharField(help_text='Base de pesquisa do Active Directory', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o dominio esta ativo ou nao')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
