# Generated by Django 6.1.1 on 2026-09-15 11:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


TARGET_APP_LABEL = "service_request"
TARGET_MODEL_NAME = "servicerequest"
TARGET_TABLE_NAME = "service_request_servicerequest"
TEMPORARY_TABLE_NAME = "service_request_legacy"


def _legacy_label():
    return "".join(("schedul", "ing"))


def stage_legacy_table(apps, schema_editor):
    legacy_label = _legacy_label()
    legacy_table_name = "_".join((legacy_label, legacy_label))
    existing_tables = set(schema_editor.connection.introspection.table_names())

    if legacy_table_name not in existing_tables:
        return

    if TARGET_TABLE_NAME in existing_tables or TEMPORARY_TABLE_NAME in existing_tables:
        raise RuntimeError("The previous service-request table cannot be migrated safely.")

    schema_editor.execute(
        schema_editor.sql_rename_table
        % {
            "old_table": schema_editor.quote_name(legacy_table_name),
            "new_table": schema_editor.quote_name(TEMPORARY_TABLE_NAME),
        }
    )


def copy_legacy_rows(apps, schema_editor):
    existing_tables = set(schema_editor.connection.introspection.table_names())
    if TEMPORARY_TABLE_NAME not in existing_tables:
        return

    columns = (
        "id",
        "public_id",
        "protocol",
        "requester_name",
        "requester_phone",
        "requester_document",
        "requester_email",
        "service_postal_code",
        "service_address",
        "service_number",
        "service_neighborhood",
        "service_landmark",
        "notes",
        "status",
        "created_at",
        "updated_at",
        "created_by_id",
        "updated_by_id",
    )
    quoted_columns = ", ".join(schema_editor.quote_name(column) for column in columns)
    schema_editor.execute(
        "INSERT INTO {target} ({columns}) SELECT {columns} FROM {source}".format(
            target=schema_editor.quote_name(TARGET_TABLE_NAME),
            source=schema_editor.quote_name(TEMPORARY_TABLE_NAME),
            columns=quoted_columns,
        )
    )
    schema_editor.execute(
        "DROP TABLE {}".format(schema_editor.quote_name(TEMPORARY_TABLE_NAME))
    )


def rename_legacy_content_type(apps, schema_editor):
    legacy_label = _legacy_label()
    database_alias = schema_editor.connection.alias
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    ServiceRequest = apps.get_model(TARGET_APP_LABEL, "ServiceRequest")

    content_types = ContentType.objects.using(database_alias)
    legacy_content_type = content_types.filter(
        app_label=legacy_label,
        model=legacy_label,
    ).first()
    if legacy_content_type is None:
        return

    target_exists = content_types.filter(
        app_label=TARGET_APP_LABEL,
        model=TARGET_MODEL_NAME,
    ).exclude(pk=legacy_content_type.pk).exists()
    if target_exists:
        raise RuntimeError("The service-request content type already exists.")

    legacy_content_type.app_label = TARGET_APP_LABEL
    legacy_content_type.model = TARGET_MODEL_NAME
    legacy_content_type.save(
        using=database_alias,
        update_fields=("app_label", "model"),
    )

    for action in ("add", "change", "delete", "view"):
        permission = Permission.objects.using(database_alias).filter(
            content_type_id=legacy_content_type.pk,
            codename=f"{action}_{legacy_label}",
        ).first()
        if permission is None:
            continue
        permission.codename = f"{action}_{TARGET_MODEL_NAME}"
        permission.name = f"Can {action} {ServiceRequest._meta.verbose_name}"
        permission.save(
            using=database_alias,
            update_fields=("codename", "name"),
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(stage_legacy_table, migrations.RunPython.noop),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("protocol", models.CharField(max_length=50, unique=True)),
                ("requester_name", models.CharField(max_length=150)),
                ("requester_phone", models.CharField(max_length=15)),
                (
                    "requester_document",
                    models.CharField(blank=True, max_length=18, null=True),
                ),
                (
                    "requester_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "service_postal_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("service_address", models.CharField(max_length=250)),
                (
                    "service_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("service_neighborhood", models.CharField(max_length=150)),
                (
                    "service_landmark",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Solicitado"),
                            ("scheduled", "Agendado"),
                            ("in_progress", "Em andamento"),
                            ("completed", "Concluído"),
                            ("canceled", "Cancelado"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_request_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_request_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de serviço",
                "verbose_name_plural": "Solicitações de serviços",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("service", models.CharField(max_length=250)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("scheduled", "Agendado"),
                            ("in_progress", "Em andamento"),
                            ("completed", "Concluído"),
                            ("canceled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_request_item_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "service_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="service_request.servicerequest",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_request_item_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da solicitação",
                "verbose_name_plural": "Itens da solicitação",
                "ordering": ["created_at"],
            },
        ),
        migrations.RunPython(copy_legacy_rows, migrations.RunPython.noop),
        migrations.RunPython(
            rename_legacy_content_type,
            migrations.RunPython.noop,
        ),
    ]
