# Generated by Django 6.1.1 on 2026-09-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0002_remove_legacy_migration_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Solicitação de serviço', 'verbose_name_plural': 'Solicitações de serviços'},
        ),
        migrations.AddField(
            model_name='servicerequestitem',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
