# Generated by Django 6.1.1 on 2026-09-15 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0002_servicetype_id_alter_servicetype_public_id'),
        ('service_request', '0003_alter_servicerequest_options_servicerequestitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequestitem',
            name='service_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='registers.servicetype'),
            preserve_default=False,
        ),
    ]
