# Generated by Django 6.1.1 on 2026-09-23 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0004_servicerequestitem_service_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequestitem',
            options={},
        ),
        migrations.AddField(
            model_name='servicerequestitem',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Serviço finalizado em'),
        ),
        migrations.AddField(
            model_name='servicerequestitem',
            name='finished_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_items_finished', to=settings.AUTH_USER_MODEL, verbose_name='Serviço finalizado por'),
        ),
        migrations.AddField(
            model_name='servicerequestitem',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_service_items', to=settings.AUTH_USER_MODEL, verbose_name='Operador'),
        ),
        migrations.AddField(
            model_name='servicerequestitem',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Serviço iniciado em'),
        ),
        migrations.AddField(
            model_name='servicerequestitem',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_items_started', to=settings.AUTH_USER_MODEL, verbose_name='Serviço iniciado por'),
        ),
        migrations.CreateModel(
            name='ServiceRequestItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_request_items/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviada em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_item_photos', to=settings.AUTH_USER_MODEL, verbose_name='Enviada por')),
                ('service_request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='service_request.servicerequestitem')),
            ],
        ),
    ]
