# Generated by Django 6.1.1 on 2026-09-24 12:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0005_alter_servicerequestitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequestitemphoto',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
